### ISSUE TITLE
n_slice undefined

### ISSUE THREAD

**Issue by pbenner** [sofyalaski/SAXS-simulations#2]
https://github.com/sofyalaski/SAXS-simulations/blob/d4a22197d74fb9a7d7f66f1f2061f87c7f6a22f5/SAXSsimulations/SAXSforward/create_form.py#L538

It seems that n_slice is not properly defined.

**Comment by sofyalaski** [comment]
That issue is fixed in the newest version. However, it takes a lot of time to rebin the whole 3D structure, not just the central slice.
Rewriting it to be faster is the next step.
